name: CI to Docker Hub

on:
  push:
    branches:
      - "arm64"
#     tags:
#       - "arm64-*"

jobs:

  arm64_v15:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}
          tags: |
            type=raw,value=latest,enable=${{ endsWith(GitHub.ref, 'main') }}
            type=raw,value=15.0-arm64
          flavor: |
            latest=false
        # with:
        #   images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}
        #   tags: |
        #     type=raw,value=latest,enable=${{ endsWith(GitHub.ref, 'main') }}
        #     type=ref,event=tag
        #     type=raw,value=15.0-arm64
        #   flavor: |
        #     latest=false
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./15.0
          file: ./15.0/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm64
          push: true
          # tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:latest
          tags: ${{ steps.meta.outputs.tags }}
      -
        name: Image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}
          free -m | awk 'NR==2{printf "Memory Usage: %s/%sMB (%.2f%%)\n", $3,$2,$3*100/$2 }'
          df -h | awk '$NF=="/"{printf "Disk Usage: %d/%dGB (%s)\n", $3,$2,$5}'
          top -bn1 | grep load | awk '{printf "CPU Load: %.2f\n", $(NF-2)}'

  arm64_v16:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}
          tags: |
            type=raw,value=latest,enable=${{ endsWith(GitHub.ref, 'main') }}
            type=raw,value=16.0-arm64
          flavor: |
            latest=false
        # with:
        #   images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}
        #   tags: |
        #     type=raw,value=latest,enable=${{ endsWith(GitHub.ref, 'main') }}
        #     type=ref,event=tag
        #     type=raw,value=16.0-arm64
        #   flavor: |
        #     latest=false
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./16.0
          file: ./16.0/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm64
          push: true
          # tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:latest
          tags: ${{ steps.meta.outputs.tags }}
      -
        name: Image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}
          free -m | awk 'NR==2{printf "Memory Usage: %s/%sMB (%.2f%%)\n", $3,$2,$3*100/$2 }'
          df -h | awk '$NF=="/"{printf "Disk Usage: %d/%dGB (%s)\n", $3,$2,$5}'
          top -bn1 | grep load | awk '{printf "CPU Load: %.2f\n", $(NF-2)}'
